apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accounts
    spec:
      containers:
      - image: http://image-registry.openshift-image-registry.svc:5000/$SN_ICR_NAMESPACE/accounts:latest
        name: accounts
        resources: {}
        
        env:
          - name: DATABASE_HOST
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: deploy
            workspaces:
              - name: manifest-dir
                workspace: pipeline-workspace
            taskRef:
              name: openshift-client
              kind: ClusterTask
            params:
            - name: SCRIPT
              value: |
                echo "Updating manifest..."
                sed -i "s|http://image-registry.openshift-image-registry.svc:5000/$SN_ICR_NAMESPACE/accounts:latest|$(params.build-image)|g" deploy/deployment.yaml
                cat deploy/deployment.yaml
                echo "Deploying to OpenShift..."
                oc apply -f deploy/
                oc get pods -l app=accounts
            runAfter:
              - build        
                
status: {}
